FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build

WORKDIR /app

EXPOSE 80

ENV ASPNETCORE_ENVIRONMENT=Development

COPY *.sln ./
COPY *.csproj ./
RUN dotnet restore

COPY . .

ENTRYPOINT ["dotnet", "watch", "run", "--no-launch-profile"]
